Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from trainer.trainer import Trainer
  File "/scratch/kap9580/new_dp_deblur/DeblurGAN-pytorch/trainer/trainer.py", line 5, in <module>
    from torchvision.utils import make_grid
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/scratch/kap9580/new_dp_deblur/penv/lib/python3.8/site-packages/PIL/__init__.py)
